from .Flinger import Flinger
from .Peon import Peon
from .Knight import Knight
from .Cannon import Cannon
from .Queen import Queen
from .King import King
from .Zombie import Zombie
from .Bishop import Bishop
from .Rook import Rook